INSERT INTO relationships ("group") VALUES ("Family");
INSERT INTO relationships ("group") VALUES ("Friends");
INSERT INTO relationships ("group") VALUES ("Co-workers");
INSERT INTO relationships ("group") VALUES ("Other");

INSERT INTO types (name) VALUES ("Professional");
INSERT INTO types (name) VALUES ("Personal");
INSERT INTO types (name) VALUES ("Other");

INSERT INTO states ("short", "name") VALUES ('AL', 'Alabama');
INSERT INTO states ("short", "name") VALUES ('AK', 'Alaska');
INSERT INTO states ("short", "name") VALUES ('AZ', 'Arizona');
INSERT INTO states ("short", "name") VALUES ('AR', 'Arkansas');
INSERT INTO states ("short", "name") VALUES ('CA', 'California');
INSERT INTO states ("short", "name") VALUES ('CO', 'Colorado');
INSERT INTO states ("short", "name") VALUES ('CT', 'Connecticut');
INSERT INTO states ("short", "name") VALUES ('DE', 'Delaware');
INSERT INTO states ("short", "name") VALUES ('FL', 'Florida');
INSERT INTO states ("short", "name") VALUES ('GA', 'Georgia');
INSERT INTO states ("short", "name") VALUES ('HI', 'Hawaii');
INSERT INTO states ("short", "name") VALUES ('ID', 'Idaho');
INSERT INTO states ("short", "name") VALUES ('IL', 'Illinois');
INSERT INTO states ("short", "name") VALUES ('IN', 'Indiana');
INSERT INTO states ("short", "name") VALUES ('IA', 'Iowa');
INSERT INTO states ("short", "name") VALUES ('KS', 'Kansas');
INSERT INTO states ("short", "name") VALUES ('KY', 'Kentucky');
INSERT INTO states ("short", "name") VALUES ('LA', 'Louisiana');
INSERT INTO states ("short", "name") VALUES ('ME', 'Maine');
INSERT INTO states ("short", "name") VALUES ('MD', 'Maryland');
INSERT INTO states ("short", "name") VALUES ('MA', 'Massachusetts');
INSERT INTO states ("short", "name") VALUES ('MI', 'Michigan');
INSERT INTO states ("short", "name") VALUES ('MN', 'Minnesota');
INSERT INTO states ("short", "name") VALUES ('MS', 'Mississippi');
INSERT INTO states ("short", "name") VALUES ('MO', 'Missouri');
INSERT INTO states ("short", "name") VALUES ('MT', 'Montana');
INSERT INTO states ("short", "name") VALUES ('NE', 'Nebraska');
INSERT INTO states ("short", "name") VALUES ('NV', 'Nevada');
INSERT INTO states ("short", "name") VALUES ('NH', 'New Hampshire');
INSERT INTO states ("short", "name") VALUES ('NJ', 'New Jersey');
INSERT INTO states ("short", "name") VALUES ('NM', 'New Mexico');
INSERT INTO states ("short", "name") VALUES ('NY', 'New York');
INSERT INTO states ("short", "name") VALUES ('NC', 'North Carolina');
INSERT INTO states ("short", "name") VALUES ('ND', 'North Dakota');
INSERT INTO states ("short", "name") VALUES ('OH', 'Ohio');
INSERT INTO states ("short", "name") VALUES ('OK', 'Oklahoma');
INSERT INTO states ("short", "name") VALUES ('OR', 'Oregon');
INSERT INTO states ("short", "name") VALUES ('PA', 'Pennsylvania');
INSERT INTO states ("short", "name") VALUES ('RI', 'Rhodeisland');
INSERT INTO states ("short", "name") VALUES ('SC', 'South Carolina');
INSERT INTO states ("short", "name") VALUES ('SD', 'South Dakota');
INSERT INTO states ("short", "name") VALUES ('TN', 'Tennessee');
INSERT INTO states ("short", "name") VALUES ('TX', 'Texas');
INSERT INTO states ("short", "name") VALUES ('UT', 'Utah');
INSERT INTO states ("short", "name") VALUES ('VT', 'Vermont');
INSERT INTO states ("short", "name") VALUES ('VA', 'Virginia');
INSERT INTO states ("short", "name") VALUES ('WA', 'Washington');
INSERT INTO states ("short", "name") VALUES ('WV', 'West Virginia');
INSERT INTO states ("short", "name") VALUES ('WI', 'Wisconsin');
INSERT INTO states ("short", "name") VALUES ('WY', 'Wyoming');