INSERT INTO relationships ("group") VALUES ("Family");
INSERT INTO relationships ("group") VALUES ("Friends");
INSERT INTO relationships ("group") VALUES ("Co-workers");
INSERT INTO relationships ("group") VALUES ("Other");

INSERT INTO types (name) VALUES ("Professional");
INSERT INTO types (name) VALUES ("Personal");
INSERT INTO types (name) VALUES ("Other");

INSERT INTO states ("short", "state") VALUES ('AL', 'ALABAMA');
INSERT INTO states ("short", "state") VALUES ('AK', 'ALASKA');
INSERT INTO states ("short", "state") VALUES ('AZ', 'ARIZONA');
INSERT INTO states ("short", "state") VALUES ('AR', 'ARKANSAS');
INSERT INTO states ("short", "state") VALUES ('CA', 'CALIFORNIA');
INSERT INTO states ("short", "state") VALUES ('CO', 'COLORADO');
INSERT INTO states ("short", "state") VALUES ('CT', 'CONNECTICUT');
INSERT INTO states ("short", "state") VALUES ('DE', 'DELAWARE');
INSERT INTO states ("short", "state") VALUES ('FL', 'FLORIDA');
INSERT INTO states ("short", "state") VALUES ('GA', 'GEORGIA');
INSERT INTO states ("short", "state") VALUES ('HI', 'HAWAII');
INSERT INTO states ("short", "state") VALUES ('ID', 'IDAHO');
INSERT INTO states ("short", "state") VALUES ('IL', 'ILLINOIS');
INSERT INTO states ("short", "state") VALUES ('IN', 'INDIANA');
INSERT INTO states ("short", "state") VALUES ('IA', 'IOWA');
INSERT INTO states ("short", "state") VALUES ('KS', 'KANSAS');
INSERT INTO states ("short", "state") VALUES ('KY', 'KENTUCKY');
INSERT INTO states ("short", "state") VALUES ('LA', 'LOUISIANA');
INSERT INTO states ("short", "state") VALUES ('ME', 'MAINE');
INSERT INTO states ("short", "state") VALUES ('MD', 'MARYLAND');
INSERT INTO states ("short", "state") VALUES ('MA', 'MASSACHUSETTS');
INSERT INTO states ("short", "state") VALUES ('MI', 'MICHIGAN');
INSERT INTO states ("short", "state") VALUES ('MN', 'MINNESOTA');
INSERT INTO states ("short", "state") VALUES ('MS', 'MISSISSIPPI');
INSERT INTO states ("short", "state") VALUES ('MO', 'MISSOURI');
INSERT INTO states ("short", "state") VALUES ('MT', 'MONTANA');
INSERT INTO states ("short", "state") VALUES ('NE', 'NEBRASKA');
INSERT INTO states ("short", "state") VALUES ('NV', 'NEVADA');
INSERT INTO states ("short", "state") VALUES ('NH', 'NEWHAMPSHIRE');
INSERT INTO states ("short", "state") VALUES ('NJ', 'NEWJERSEY');
INSERT INTO states ("short", "state") VALUES ('NM', 'NEWMEXICO');
INSERT INTO states ("short", "state") VALUES ('NY', 'NEWYORK');
INSERT INTO states ("short", "state") VALUES ('NC', 'NORTHCAROLINA');
INSERT INTO states ("short", "state") VALUES ('ND', 'NORTHDAKOTA');
INSERT INTO states ("short", "state") VALUES ('OH', 'OHIO');
INSERT INTO states ("short", "state") VALUES ('OK', 'OKLAHOMA');
INSERT INTO states ("short", "state") VALUES ('OR', 'OREGON');
INSERT INTO states ("short", "state") VALUES ('PA', 'PENNSYLVANIA');
INSERT INTO states ("short", "state") VALUES ('RI', 'RHODEISLAND');
INSERT INTO states ("short", "state") VALUES ('SC', 'SOUTHCAROLINA');
INSERT INTO states ("short", "state") VALUES ('SD', 'SOUTHDAKOTA');
INSERT INTO states ("short", "state") VALUES ('TN', 'TENNESSEE');
INSERT INTO states ("short", "state") VALUES ('TX', 'TEXAS');
INSERT INTO states ("short", "state") VALUES ('UT', 'UTAH');
INSERT INTO states ("short", "state") VALUES ('VT', 'VERMONT');
INSERT INTO states ("short", "state") VALUES ('VA', 'VIRGINIA');
INSERT INTO states ("short", "state") VALUES ('WA', 'WASHINGTON');
INSERT INTO states ("short", "state") VALUES ('WV', 'WESTVIRGINIA');
INSERT INTO states ("short", "state") VALUES ('WI', 'WISCONSIN');
INSERT INTO states ("short", "state") VALUES ('WY', 'WYOMING');

